spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.253.134:7001
        - 192.168.253.134:7002
        - 192.168.253.134:7003
        - 192.168.253.134:7004
        - 192.168.253.134:7005
        - 192.168.253.134:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.253.128
    username: admin
    password: 123456
    virtual-host: /
#配置缓存首页商品分类的 key
PORTAL_CATRESULT_KEY: PORTAL_CATRESULT_KEY
#商品详情
ITEM_INFO_BASE: ITEM_INFO_BASE
ITEM_INFO_DESC: ITEM_INFO_DESC
ITEM_INFO_PARAM: ITEM_INFO_PARAM
ITEM_INFO_EXPIRE: 86400
#分布式锁
SETNX_BASC_LOCK_KEY: SETNX_BASC_LOCK_KEY
SETNX_DESC_LOCK_KEY: SETNX_DESC_LOCK_KEY
SETNX_PARAM_LOCK_KEY: SETNX_PARAM_LOCK_KEY
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/